PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT DISTINCT ?s ?label
WHERE {
  ?s ?p ?o .
  OPTIONAL {
	?s rdfs:label ?label .
  }
  FILTER STRSTARTS(STR(?s), "http://purl.obolibrary.org/obo/")
}
ORDER BY ?s
